on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Build and deploy to EC2
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t ${{ secrets.DOCKER_USER }}/email_agent:latest .
          docker push ${{ secrets.DOCKER_USER }}/email_agent:latest
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH }}
          script: |
            if ! command -v docker &> /dev/null; then
              sudo dnf install -y docker
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER
            fi
            docker pull ${{ secrets.DOCKER_USER }}/email_agent:latest
            docker image prune -f 